### PR TITLE
Profile save fix, using local ICAO file if it exists, removed tag dragging in APP window

### PR DESCRIPTION
**Pull request by LB767**
@pierr3 I had to remove the VS project files from my repo because some paths in them were conflicting with yours. So ignore these being deleted if you want.

### CODE REVIEW

**Comment by pierr3** [comment]
@LB767 could you add a commit to this putting the original vs files back? I don't have access to a computer for a bit and if you I'd be able to merge and build with the CI

**Comment by LB767** [comment]
I can try... (I'm not optimistic considering my abysmal Git knowledge xD)

**Comment by LB767** [comment]
Right, hopefully should be good now

**Comment by pierr3** [comment]
Took me a while to merge due to holiday, but its done now, have a try on the nightly! Many thanks @LB767 :D

**Pull request merged**
