### PR TITLE
Issue #30 and Telex polishing

### PR DESCRIPTION
**Pull request by DrFreas**
If there is a request which contains "LOGON", it will automatically answer "UNABLE".
Also, when a Telex-message has been received and got answered, it will now remove the Telex-message and thus makes it possible, that the "message sent" flag will show properly.

### CODE REVIEW

**Comment by keanucz** [comment]
Make sure to pull in changes from the git repo's master branch ;)

**Comment by DrFreas** [comment]
I have, is there a function I am not aware of?

**Comment by keanucz** [comment]
I made some changes earlier, and looking at your branch it says "This branch is 2 commits ahead, 17 commits behind pierr3:master.", the 17 commits are my commits, so if you git pull from the original master branch then it will include all my changes as well as yours

**Comment by DrFreas** [comment]
Well, I thought I had, apparently I haven't. Thanks for the heads up!

**Comment by keanucz** [comment]
No worries, I almost forgot to include your other changes in my pull request!

**Comment by pierr3** [comment]
Thanks @DrFreas ! Merged, this was highly requested, thank you very much.

**Pull request merged**
