### PR TITLE
Changed handling of callsign tag item selection.

### PR DESCRIPTION
**Pull request by sw104**
I have not tested this - but it should allow the opening of the handoff menu when middle clicking the callsign tag item which I do not think is currently possible.

### CODE REVIEW

**Comment by pierr3** [comment]
Why middle clicking? Does right clicking not work?

**Comment by pierr3** [comment]
Disregard, I just understood what you mean.

**Comment by LB767** [comment]
Just tested this, pretty sure it should be a `&&` instead of a `||` in `if (Button != BUTTON_RIGHT || Button != BUTTON_MIDDLE)`
I'll try to put my updated code on here once I figure out how to use this github thing

**Comment by sw104** [comment]
Apologies, indeed it should be a logical `AND` instead of `OR`.

**Pull request merged**
