### PR TITLE
Added ground status tag

### PR DESCRIPTION
**Pull request by blt950**
Added ground status tag option, with menu to change when you right click on it.

It's something I felt personally I was missing, but I understand if its not part of the simulated environment and not included because of it.

gtag2

### CODE REVIEW

**Comment by pierr3** [comment]
I've never added it because it does not exist in the real thing, and it makes more sense just to "look" at the position of the aircraft to know if its taxiing than having to read about it. But since you've done it, I'm willing to merge it. However, you will need to revert your commit changing the plugin description. I'll update the version myself.

**Comment by blt950** [comment]
Indeed, that's why I was unsure it would fit in as it's not in the real thing. I removed the commit as asked, it wasn't supposed to be part of this pull anyway, was more for testing and make it distinct :)

**Comment by pierr3** [comment]
Thanks, merged it and I'll add your name to the contributors list :)

**Comment by nickbotica** [comment]
Just a heads up, if the "groundstatus_colors" push, taxi and dep aren't defined in the json the program will crash once you start painting targets.
I was going to contribute something back but there are a number of ways you could choose to deal with it.
The simplest is to add them of the json. A safer but perhaps not effiencnt way would be to check if the rapidjson HasMember("groundstatus_colors") first and set a default white if not.
Cheers

**Pull request merged**
