### PR TITLE
TELEX messages

### PR DESCRIPTION
**Pull request by DrFreas**
I modified the code slightly to be able to send TELEX messages. The window will be the same as the clearence window, but only the message field will be sent.
Also some little changes to be able to use different types of messages (CPDLC and TELEX) but only using one function.

### CODE REVIEW

**Comment by pierr3** [comment]
Thank you so much for the contribution 😄 It's truly appreciated.

Just to confirm, your proposed change would include a new option in the dropdown which would allow you to use the same poppup, and only send the Message box by TELEX?

If so, would this not cause a problem since you are not able to view TELEX messages replies? And what is your intended purpose for this feature?

Finally, how much testing have you done of this code? :)

**Comment by DrFreas** [comment]
Yes, indeed.
The purpose would be to be able to do for example pushback clearences (I've been asked in the past if that's possible) or even to send updated QNH, whatever you want to send. Maybe some thunderstorm info.
And yes, indeed it doesn't show that you got a message but if you know you got a message, you can see it :) Couldn't try that much yet because not many people use ACARS where I control... :( So I had to lend a callsign from someone who shows up in the list and send messages back and forth. So there would be a need for a function that shows when a message is received... Haven't thought of that yet, to be honest :) I will have a look into that right now, I'm sure there will be a solution for that.
Maybe a blinking "T" for every message that isn't a clearence request?

**Comment by DrFreas** [comment]
So I added the function that if there is an incoming message that isn't a CPDLC or Wilco or whatnot will show as a yellow "T" in the list. 
I used it for several hours now and it works fine! All messages get through and it's great to deliver more information in the clearence, for example when you forgot to set the initial climb clearence :D 
My vision would be a dedicated window though and the option to send and receive messages from aircrafts which aren't showing in a list.

**Comment by pierr3** [comment]
Thanks for testing and the edits, would anyone else be able to test this branch independently to make sure it's all good?

**Comment by ghost** [comment]
I will check it out since I regularly use CPDLC when I control France Upper and Domestic.

**Comment by keanucz** [comment]
How's it looking?

**Comment by pierr3** [comment]
Looking to merge this ahead of bigger merge by @Keanu73, any feedback on this? Otherwise will merge.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DrFreas** [comment]
I did two little adjustments in the code, where "Message" in the dropdown menu is always active now and since one pilot mentioned last week or so that he hasn't got a TELEX from me (but it was flagged as "received" in the hoppie log) I did a small adjustment in the format of the message, so it won't be sent with "&packet=/data2/". I don't know if this fixes that yet though. It worked for other pilots in the past in the way it was.

**Comment by DrFreas** [comment]
Luckily today I had the opportunity to test this function extendedly with a pilot and the only issue I found is that when a telex has been sent and the yellow "V" is shown, it wouldn't show when there is a new message. To fix that, I adjusted the sequence of the "algorithm" that checks for every vector.
So I can say that it works like a charm now (for me at least). The pilot used an A320, I don't know which one exactly.

**Comment by pierr3** [comment]
Thanks for this!

**Pull request merged**
